/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qml_Bridge */

#ifndef _Included_qml_Bridge
#define _Included_qml_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qml_Bridge
 * Method:    initialize
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_initialize
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     qml_Bridge
 * Method:    loadQml
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qml_Bridge_loadQml
  (JNIEnv *, jclass, jstring);

/*
 * Class:     qml_Bridge
 * Method:    setContextProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_setContextProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     qml_Bridge
 * Method:    exec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qml_Bridge_exec
  (JNIEnv *, jclass);

/*
 * Class:     qml_Bridge
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_quit
  (JNIEnv *, jclass);

/*
 * Class:     qml_Bridge
 * Method:    registerSignalHandler
 * Signature: (Ljava/lang/String;Lqml/Bridge/SignalHandler;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_registerSignalHandler
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     qml_Bridge
 * Method:    createModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_createModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     qml_Bridge
 * Method:    setModelData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_setModelData
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     qml_Bridge
 * Method:    clearModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_clearModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     qml_Bridge
 * Method:    getModelCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_qml_Bridge_getModelCount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     qml_Bridge
 * Method:    setAutoReload
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_qml_Bridge_setAutoReload
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     qml_Bridge
 * Method:    isAutoReloadEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_qml_Bridge_isAutoReloadEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
